[package]
name = "cstr8"
version = "0.1.0"
edition = "2021"
rust-version = "1.59.0"

description = "string types that are both valid UTF-8 and nul-terminated"
license = "MIT OR Apache-2.0"
keywords = ["cstr", "zstr", "string8_t", "char8_t", "cstring8"]
categories = ["development-tools::ffi", "rust-patterns"]

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
thiserror = "1.0.31"
