name: CI
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  feats:
    name: Check features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.72 # MSRV
      - name: Check (-std -alloc)
        run: cargo check --lib --no-default-features
      - name: Check (-std +alloc)
        run: cargo check --lib --no-default-features --features alloc
      - name: Check (+std +alloc)
        run: cargo check --lib --no-default-features --features alloc,std

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.72 # MSRV
      - name: Build tests
        run: cargo test --no-run
      - name: Run tests
        run: cargo test

  style:
    name: Style tests
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Install cargo-docs-rs
        uses: dtolnay/install@cargo-docs-rs
      - name: Check documentation build
        run: cargo docs-rs
      - name: Check clippy lints
        run: cargo clippy -- -D warnings
      - name: Check formatting
        run: cargo fmt -- --check
